In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
%matplotlib inline

import missingno as msno

In [4]:
df = pd.read_csv('/content/drive/MyDrive/슬기로운 건강생활/data/국민건강보험공단_건강검진정보_20211229.CSV', encoding='cp949')
df

,기준년도,가입자 일련번호,시도코드,성별코드,연령대 코드(5세단위),신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석,데이터 공개일자
0,2020,1,36,1,9,165,60,72.1,1.2,1.5,...,1.1,21.0,27.0,21.0,1.0,0.0,0,NaN,NaN,2021-12-29
1,2020,2,27,2,13,150,65,81.0,0.8,0.8,...,0.5,18.0,15.0,15.0,1.0,0.0,0,NaN,NaN,2021-12-29
2,2020,3,11,2,12,155,55,70.0,0.6,0.7,...,0.7,27.0,25.0,7.0,1.0,0.0,0,NaN,NaN,2021-12-29
3,2020,4,31,1,13,160,70,90.8,1.0,1.0,...,1.2,65.0,97.0,72.0,1.0,0.0,1,0.0,0.0,2021-12-29
4,2020,5,41,2,12,155,50,75.2,1.5,1.2,...,0.7,18.0,17.0,14.0,1.0,0.0,0,NaN,NaN,2021-12-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2020,999996,41,2,13,145,55,81.0,0.9,1.0,...,0.6,21.0,25.0,18.0,1.0,0.0,0,NaN,NaN,2021-12-29
999996,2020,999997,26,2,12,160,55,76.5,1.5,1.5,...,0.8,21.0,14.0,19.0,1.0,1.0,0,NaN,NaN,2021-12-29
999997,2020,999998,48,1,9,175,70,85.0,1.2,1.2,...,0.9,26.0,20.0,17.0,1.0,1.0,0,NaN,NaN,2021-12-29
999998,2020,999999,48,2,9,160,70,91.0,0.6,0.5,...,1.0,25.0,29.0,13.0,1.0,0.0,0,NaN,NaN,2021-12-29
999999,2020,1000000,28,1,11,160,55,76.1,2.0,2.0,...,0.9,17.0,13.0,24.0,2.0,0.0,0,NaN,NaN,2021-12-29

In [5]:
df.columns

Index(['기준년도', '가입자 일련번호', '시도코드', '성별코드', '연령대 코드(5세단위)', '신장(5Cm단위)',
       '체중(5Kg 단위)', '허리둘레', '시력(좌)', '시력(우)', '청력(좌)', '청력(우)', '수축기 혈압',
       '이완기 혈압', '식전혈당(공복혈당)', '총 콜레스테롤', '트리글리세라이드', 'HDL 콜레스테롤', 'LDL 콜레스테롤',
       '혈색소', '요단백', '혈청크레아티닌', '(혈청지오티)AST', '(혈청지오티)ALT', '감마 지티피', '흡연상태',
       '음주여부', '구강검진 수검여부', '치아우식증유무', '치석', '데이터 공개일자'],
      dtype='object')

In [6]:
corr_df = df.corr()
corr_df = corr_df.apply(lambda x: round(x ,2))

#신장(5Cm단위)
- 체중(5Kg 단위)

In [8]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["신장(5Cm단위)"].sort_values(ascending = False))  #Price에 대한 다른 변수 수치 뽑기, 내림차순 정렬
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

#체중(5Kg 단위)
- 허리둘레
- 신장(5Cm단위)

In [9]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["체중(5Kg 단위)"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

#허리둘레
- 체중(5Kg 단위)

In [10]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["허리둘레"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

#시력(좌)

In [11]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["시력(좌)"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

#시력(우)

In [12]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["시력(우)"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [7]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["청력(좌)"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [8]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["청력(우)"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [10]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["수축기 혈압"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [11]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["이완기 혈압"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [12]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["식전혈당(공복혈당)"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [13]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["총 콜레스테롤"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [14]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["트리글리세라이드"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [15]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["HDL 콜레스테롤"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [16]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["LDL 콜레스테롤"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [17]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["혈색소"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [18]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["요단백"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [19]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["혈청크레아티닌"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [20]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["(혈청지오티)AST"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [21]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["(혈청지오티)ALT"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [22]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["감마 지티피"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [23]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["흡연상태"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [24]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["음주여부"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [25]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["구강검진 수검여부"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [26]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["치아우식증유무"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기

In [27]:
# 총 콜레스테롤 에 대한 다른 변수들의 상관관계
co = pd.DataFrame(corr_df["치석"].sort_values(ascending = False))
co.style.background_gradient(cmap='viridis')    #스타일 지정해서 범위 별 색깔 입히기